version: "3.9"

services:

  node:
    image: node:16
    container_name: car_shop
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    environment:
      - PORT=${PORT}
      - MONGO_URI=mongodb://mongodb:27017/CarShop
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    ports:
      - 3001:3001
    
  mongodb:
    image: mongo:5.0.7
    container_name: car_shop_db
    environment:
      - MONGO_PORT=${MONGO_PORT}
    volumes:
      - ./:/app
    restart: always
    ports:
      - 27017:27017

networks:
  default:
    name: car_shop_net

