version: "3.9"

services:
  node:
    image: node:16
    container_name: car_shop
    tty: true
    stdin_open: true
    command: bash
    restart: always
    working_dir: /app
    environment:
      - PORT=${PORT}
    volumes:
      - ./:/app
    depends_on:
      - mongodb
    ports:
      - ${PORT}:3001

  mongodb:
    image: mongo:5.0.7
    container_name: car_shop_db
    environment:
      - MONGO_PORT=${MONGO_PORT}
    volumes:
      - ./:/app
    restart: always
    ports:
      - ${MONGO_PORT}:27017

networks:
  default:
    name: car_shop_net

